#cloud-config
package_update: true
package_upgrade: true
packages:
    - git
    - curl
    - build-essential
    - jq
    - wget
final_message: "The system is finally up, after $UPTIME seconds"
output: {all: '| tee -a /var/log/cloud-init-output.log'}
